FROM apache/airflow:2.10.5

# copia a lista de libs do Airflow e instala "assando" na imagem
COPY requirements-airflow.txt /requirements-airflow.txt
RUN pip install --no-cache-dir -r /requirements-airflow.txt